const customMapping: { [key: string]: string } = {
    php: "php",
    cs: "csharp",
    "c#": "csharp",
    js: "javascript",
    ts: "typescript",
    py: "python",
    rb: "ruby",
    java: "java",
    cpp: "cpp",
    "c++": "cpp",
    c: "c",
    go: "go",
    rust: "rust",
    swift: "swift",
    kotlin: "kotlin",
    scala: "scala",
    html: "html",
    css: "css",
    scss: "sass",
    sass: "sass",
    less: "less",
    json: "json",
    xml: "xml",
    yaml: "yaml",
    yml: "yaml",
    markdown: "markdown",
    md: "markdown",
    sql: "sql",
    shell: "shell",
    sh: "shell",
    bash: "shell",
    powershell: "powershell",
    dockerfile: "dockerfile",
    jsx: "jsx",
    tsx: "tsx",
    vue: "vue",
    angular: "angular",
    // Maybe add more languages here
}

export default customMapping
